{{- if .Values.airflow.oauth.enable }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-google-oauth
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  googleClientID: '{{ .Values.googleOauth.clientID | b64enc }}'
  googleClientSecret: '{{ .Values.googleOauth.clientSecret | b64enc }}'
{{- end }}
