{{- define "connections.script" }}
  #!/bin/sh -e
  {{- range  $key, $value := .Values.airflow.connections }}
  airflow connections --delete --conn_id '{{ $key }}' 
  echo "Adding connection '{{ $key }}'"
  airflow connections --add --conn_id '{{ $key }}' --conn_type '{{ $value.type }}'
  {{- if $value.uri }} --conn_uri '{{ $value.uri }}' {{ end -}}
  {{- if $value.host }} --conn_host '{{ $value.host }}' {{ end -}}
  {{- if $value.login }} --conn_login '{{ $value.login }}' {{ end -}}
  {{- if $value.password }} --conn_password '{{ $value.password }}' {{ end -}}
  {{- if $value.schema }} --conn_schema '{{ $value.schema }}' {{ end -}}
  {{- if $value.port }} --conn_port {{ .port }} {{ end -}}
  {{- if $value.extra }} --conn_extra '{{ $value.extra }}' {{ end -}}
  2>/dev/null >/dev/null
  {{- end }}
{{- end }}
{{- if .Values.airflow.connections }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-connections
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  add-connections.sh: {{ include "connections.script" . | b64enc }}
{{- end }}
