---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-airflow
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.awsInitDB.enable }}
  masterPostgresUser: '{{ .Values.postgresql.postgresUser | b64enc }}'
  masterPostgresPassword: '{{ .Values.postgresql.postgresPassword | b64enc }}'
{{- end  }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-secret-env
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.awsPostgresHost }}
  POSTGRES_HOST: '{{ .Values.awsPostgresHost | b64enc }}'
{{- else }}
  POSTGRES_HOST: '{{ (print $.Release.Name "-postgresql") | b64enc }}'
{{- end }}
  POSTGRES_USER: '{{ .Values.postgresql.EntrypointInitDB.projectUser | b64enc }}'
  POSTGRES_PASSWORD: '{{ .Values.postgresql.EntrypointInitDB.projectPass | b64enc }}'
  REDIS_PASSWORD: '{{ .Values.redis.password | b64enc }}'
  FERNET_KEY: '{{ .Values.airflow.fernetKey | b64enc }}'
  {{- range $setting, $option := .Values.airflow.secretEnv }}
  {{ $setting }}: '{{ $option | b64enc }}'
  {{- end }}

{{- $root := . -}}
{{- range .Values.additionalResources.secret2File }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" $root }}-{{ .name }}
  labels:
    chart: {{ $root.Chart.Name }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  {{- range $setting, $option := .data }}
  {{ $setting }}: {{ $option | b64enc }}
  {{- end }}
{{- end }}
