---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-git-key
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ssh: '{{ .Values.airflow.secrets.gitDeployKey | b64enc }}'
