{{- if .Values.airflow.serviceMonitor }}
{{- if .Values.monitoring }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "airflow.fullname" . }}-overall
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: {{ .Chart.Name }}
spec:
  jobLabel: app
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 29s
  selector: {}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
    - ingress
{{- if .Values.airflow.metrics }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "airflow.fullname" . }}-web
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: {{ .Chart.Name }}
spec:
  jobLabel: app
  endpoints:
  - port: web
    path: /admin/metrics
    interval: 60s
    scrapeTimeout: 59s
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-web
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
