repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.13.1
    wait: true
    timeout: 300
    values:
      - ../values/cert-manager-values.yaml
