repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com/

environments:
  default:
    values:
    - ../airflow/values/default.yaml

releases:
  - name: prometheus-adapter
    namespace: monitoring
    chart: stable/prometheus-adapter
    version: 2.3.1
    wait: true
    timeout: 300
    values:
      - ../values/prometheus-adapter.yaml

