---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "airflow.fullname" . }}-flower-pip-requirements
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  requirements.txt: |-
{{- if .Values.airflow.flower.pythonModules }}
  {{- range .Values.airflow.flower.pythonModules }}
    {{ . }}
  {{- end }}
{{- end }}
{{- if .Values.airflow.pythonModules }}
  {{- range .Values.airflow.pythonModules }}
    {{ . }}
  {{- end }}
{{- end }}
